"""
trainer_blindspot.py

Training and validation pipeline for the BlindSpot occupancy
classification model.

The model receives two consecutive fisheye-camera frames:

    image_prev
    image_curr

and predicts two raw occupancy logits:

    occupancy_logits[:, 0] -> FREE
    occupancy_logits[:, 1] -> OCCUPIED

Training configuration:

    - Loss:
        CrossEntropyLoss

    - Optimizer:
        SGD with momentum and Nesterov acceleration

    - Learning-rate scheduler:
        Linear warmup followed by linear decay

    - Model weight smoothing:
        Exponential Moving Average (EMA)

    - Best-model criterion:
        Validation F1 score

    - Validation metrics:
        Loss
        Accuracy
        Precision
        Recall
        F1 score
        TP, TN, FP, FN

The trainer consumes metadata files generated by parse_woodscape.py
and loads the data through load_woodscape.py.
"""

import argparse
import copy
import logging
import os
import shutil
from datetime import datetime
from pathlib import Path

import torch
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm

import blindspot_util as util

from Models.data_parsing.load_woodscape import create_dataloader
from Models.model_components.blindspot.blindspot_network import BlindSpot


# ----------------------------------------------------------------------
# Logging
# ----------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(__name__)


# ----------------------------------------------------------------------
# Default training configuration
# ----------------------------------------------------------------------

DEFAULT_MAX_LR = 0.01
DEFAULT_MIN_LR = 0.0001
DEFAULT_MOMENTUM = 0.937
DEFAULT_WEIGHT_DECAY = 0.0005
DEFAULT_WARMUP_EPOCHS = 1.0


def create_run_directory(
    runs_dir: Path,
    output_subdir: str | None = None,
) -> Path:
    """
    Create the output directory for one training run.

    If output_subdir is provided, that directory is recreated.
    Otherwise, a unique timestamped directory is generated.
    """

    runs_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    if output_subdir is not None:

        run_dir = runs_dir / output_subdir

        if run_dir.exists():
            logger.warning(
                "Removing existing output directory: %s",
                run_dir,
            )
            shutil.rmtree(run_dir)

        run_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        return run_dir

    timestamp = datetime.now().strftime(
        "%Y-%m-%d_%H-%M-%S"
    )

    base_name = f"run_{timestamp}"
    run_dir = runs_dir / base_name

    suffix = 0

    while run_dir.exists():
        suffix += 1
        run_dir = runs_dir / f"{base_name}_{suffix:02d}"

    run_dir.mkdir(
        parents=True,
        exist_ok=False,
    )

    return run_dir


def create_model(
    device: torch.device,
    autospeed_checkpoint: str | None,
) -> BlindSpot:
    """
    Create the BlindSpot model and optionally initialize its
    backbone from a trained AutoSpeed checkpoint.

    Only the backbone parameters are transferred. The BlindSpot
    occupancy head remains task-specific and starts from its own
    initialization.
    """

    model = BlindSpot()

    if autospeed_checkpoint is not None:

        logger.info(
            "Initializing BlindSpot backbone from AutoSpeed: %s",
            autospeed_checkpoint,
        )

        model.load_backbone_from_autospeed(
            autospeed_checkpoint
        )

    else:

        logger.warning(
            "No AutoSpeed checkpoint provided. "
            "The BlindSpot backbone will start from its "
            "default initialization."
        )

    model = model.to(device)

    return model


def create_optimizer(
    model: torch.nn.Module,
    batch_size: int,
    world_size: int,
    params: dict,
):
    """
    Create the SGD optimizer used for BlindSpot V1.

    Weight decay is scaled according to the effective batch size,
    following the same training convention used by AutoSpeed and
    AutoSteer.

    Biases and normalization parameters are excluded from weight
    decay through util.set_params().
    """

    accumulate = max(
        round(
            64 /
            (batch_size * world_size)
        ),
        1,
    )

    scaled_weight_decay = (
        params["weight_decay"]
        * batch_size
        * world_size
        * accumulate
        / 64
    )

    optimizer = torch.optim.SGD(
        util.set_params(
            model,
            scaled_weight_decay,
        ),
        lr=params["min_lr"],
        momentum=params["momentum"],
        nesterov=True,
    )

    logger.info(
        "Optimizer: SGD, min_lr=%.6f, max_lr=%.6f, "
        "momentum=%.4f, scaled_weight_decay=%.6f",
        params["min_lr"],
        params["max_lr"],
        params["momentum"],
        scaled_weight_decay,
    )

    logger.info(
        "Gradient accumulation steps: %d",
        accumulate,
    )

    return optimizer, accumulate


def save_checkpoint(
    checkpoint_path: Path,
    epoch: int,
    model: torch.nn.Module,
    metrics: dict,
    train_loss: float,
    val_loss: float,
) -> None:
    """
    Save the EMA model and corresponding training information.

    The full model object is saved to remain compatible with the
    existing project checkpoint style and the AutoSpeed backbone
    loading mechanism.
    """

    checkpoint = {
        "epoch": epoch,
        "model": copy.deepcopy(model),
        "train_loss": train_loss,
        "val_loss": val_loss,
        "metrics": metrics,
    }

    torch.save(
        checkpoint,
        checkpoint_path,
    )

    logger.info(
        "Saved checkpoint: %s",
        checkpoint_path,
    )


def train_one_epoch(
    model: torch.nn.Module,
    train_loader,
    criterion,
    optimizer,
    scheduler,
    ema,
    device: torch.device,
    epoch: int,
    epochs: int,
    accumulate: int,
    use_amp: bool,
    writer: SummaryWriter,
):
    """
    Train the BlindSpot model for one epoch.

    Each batch contains:

        image_prev : (B, 3, 512, 1024)
        image_curr : (B, 3, 512, 1024)
        occupancy  : (B,)

    The model returns:

        occupancy_logits : (B, 2)

    CrossEntropyLoss compares these raw logits against integer
    labels:

        0 -> FREE
        1 -> OCCUPIED
    """

    model.train()

    average_loss = util.AverageMeter()

    optimizer.zero_grad(
        set_to_none=True
    )

    progress_bar = tqdm(
        enumerate(train_loader),
        total=len(train_loader),
        desc=f"Train {epoch}/{epochs}",
    )

    for batch_index, batch in progress_bar:

        global_step = (
            (epoch - 1) * len(train_loader)
            + batch_index
        )

        scheduler.step(
            global_step,
            optimizer,
        )

        image_prev = batch["image_prev"].to(
            device,
            non_blocking=True,
        )

        image_curr = batch["image_curr"].to(
            device,
            non_blocking=True,
        )

        occupancy = batch["occupancy"].to(
            device,
            non_blocking=True,
        )

        batch_size = occupancy.size(0)

        # PyTorch automatic mixed precision reduces GPU memory use
        # and can improve training throughput. It is disabled when
        # --fp32 is selected or when training on CPU.
        with torch.autocast(
            device_type=device.type,
            dtype=torch.float16,
            enabled=use_amp,
        ):

            occupancy_logits = model(
                image_prev,
                image_curr,
            )

            loss = criterion(
                occupancy_logits,
                occupancy,
            )

            # Divide the loss so accumulated gradients have
            # approximately the same scale as one large batch.
            scaled_loss = loss / accumulate

        scaled_loss.backward()

        should_optimize = (
            (batch_index + 1) % accumulate == 0
            or (batch_index + 1) == len(train_loader)
        )

        if should_optimize:

            optimizer.step()

            optimizer.zero_grad(
                set_to_none=True
            )

            # EMA is updated only after an actual optimizer update,
            # not after every gradient-accumulation micro-batch.
            ema.update(model)

        average_loss.update(
            loss.item(),
            batch_size,
        )

        current_lr = optimizer.param_groups[0]["lr"]

        progress_bar.set_postfix(
            loss=f"{average_loss.avg:.4f}",
            lr=f"{current_lr:.6f}",
        )

    writer.add_scalar(
        "Loss/train",
        average_loss.avg,
        epoch,
    )

    writer.add_scalar(
        "LearningRate",
        optimizer.param_groups[0]["lr"],
        epoch,
    )

    return average_loss.avg


@torch.no_grad()
def validate(
    model: torch.nn.Module,
    val_loader,
    criterion,
    device: torch.device,
    epoch: int,
    epochs: int,
    use_amp: bool,
):
    """
    Evaluate the EMA model on the validation dataset.

    F1 score is the primary model-selection metric because it
    balances precision and recall.

    Recall is particularly important for BlindSpot because a false
    negative represents an OCCUPIED blindspot incorrectly classified
    as FREE.
    """

    model.eval()

    average_loss = util.AverageMeter()

    all_targets = []
    all_predictions = []

    progress_bar = tqdm(
        val_loader,
        total=len(val_loader),
        desc=f"Val   {epoch}/{epochs}",
    )

    for batch in progress_bar:

        image_prev = batch["image_prev"].to(
            device,
            non_blocking=True,
        )

        image_curr = batch["image_curr"].to(
            device,
            non_blocking=True,
        )

        occupancy = batch["occupancy"].to(
            device,
            non_blocking=True,
        )

        with torch.autocast(
            device_type=device.type,
            dtype=torch.float16,
            enabled=use_amp,
        ):

            occupancy_logits = model(
                image_prev,
                image_curr,
            )

            loss = criterion(
                occupancy_logits,
                occupancy,
            )

        predictions = torch.argmax(
            occupancy_logits,
            dim=1,
        )

        average_loss.update(
            loss.item(),
            occupancy.size(0),
        )

        all_targets.extend(
            occupancy.detach().cpu().tolist()
        )

        all_predictions.extend(
            predictions.detach().cpu().tolist()
        )

        progress_bar.set_postfix(
            loss=f"{average_loss.avg:.4f}"
        )

    if not all_targets:
        raise RuntimeError(
            "Validation produced no samples. "
            "Check val_metadata.json and the validation DataLoader."
        )

    metrics = util.compute_classification_metrics(
        all_targets,
        all_predictions,
    )

    return average_loss.avg, metrics


def log_validation_results(
    writer: SummaryWriter,
    epoch: int,
    val_loss: float,
    metrics: dict,
) -> None:
    """
    Log validation metrics to TensorBoard.

    TP, TN, FP, and FN are also logged because they clearly show
    whether errors are nuisance warnings or missed occupancy events.
    """

    writer.add_scalar(
        "Loss/val",
        val_loss,
        epoch,
    )

    writer.add_scalar(
        "Metrics/accuracy",
        metrics["accuracy"],
        epoch,
    )

    writer.add_scalar(
        "Metrics/precision",
        metrics["precision"],
        epoch,
    )

    writer.add_scalar(
        "Metrics/recall",
        metrics["recall"],
        epoch,
    )

    writer.add_scalar(
        "Metrics/f1",
        metrics["f1"],
        epoch,
    )

    writer.add_scalar(
        "ConfusionMatrix/TP",
        metrics["tp"],
        epoch,
    )

    writer.add_scalar(
        "ConfusionMatrix/TN",
        metrics["tn"],
        epoch,
    )

    writer.add_scalar(
        "ConfusionMatrix/FP",
        metrics["fp"],
        epoch,
    )

    writer.add_scalar(
        "ConfusionMatrix/FN",
        metrics["fn"],
        epoch,
    )


def train(args) -> None:
    """
    Run the complete BlindSpot training and validation workflow.
    """

    util.setup_seed(
        args.seed
    )

    util.setup_multi_processes()

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    if device.type == "cuda":

        device_id = torch.cuda.current_device()
        device_name = torch.cuda.get_device_name(
            device_id
        )

        logger.info(
            "Using GPU %d: %s",
            device_id,
            device_name,
        )

    else:

        logger.warning(
            "CUDA is not available. Training will run on CPU."
        )

    use_amp = (
        device.type == "cuda"
        and not args.fp32
    )

    logger.info(
        "Training precision: %s",
        "FP16 automatic mixed precision"
        if use_amp
        else "FP32",
    )

    run_dir = create_run_directory(
        Path(args.runs_dir),
        args.output_subdir,
    )

    weights_dir = run_dir / "weights"
    weights_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    logger.info(
        "Run directory: %s",
        run_dir,
    )

    writer = SummaryWriter(
        log_dir=run_dir
    )

    train_loader = create_dataloader(
        metadata_file=args.train_metadata,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
    )

    val_loader = create_dataloader(
        metadata_file=args.val_metadata,
        batch_size=args.val_batch_size,
        shuffle=False,
        num_workers=args.num_workers,
    )

    if len(train_loader) == 0:
        raise RuntimeError(
            "The training DataLoader is empty."
        )

    if len(val_loader) == 0:
        raise RuntimeError(
            "The validation DataLoader is empty."
        )

    logger.info(
        "Training batches: %d",
        len(train_loader),
    )

    logger.info(
        "Validation batches: %d",
        len(val_loader),
    )

    model = create_model(
        device=device,
        autospeed_checkpoint=args.autospeed_checkpoint,
    )

    parameters = {
        "max_lr": args.max_lr,
        "min_lr": args.min_lr,
        "momentum": args.momentum,
        "weight_decay": args.weight_decay,
        "warmup_epochs": args.warmup_epochs,
    }

    optimizer, accumulate = create_optimizer(
        model=model,
        batch_size=args.batch_size,
        world_size=1,
        params=parameters,
    )

    scheduler = util.LinearLR(
        args=args,
        params=parameters,
        num_steps=len(train_loader),
    )

    # CrossEntropyLoss expects:
    #
    #   inputs : raw logits with shape (B, 2)
    #   targets: integer labels with shape (B,)
    #
    # No softmax should be applied inside the model.
    criterion = torch.nn.CrossEntropyLoss()

    ema = util.EMA(model)

    best_f1 = -1.0

    best_checkpoint = weights_dir / "best.pt"
    last_checkpoint = weights_dir / "last.pt"

    try:

        for epoch in range(
            1,
            args.epochs + 1,
        ):

            logger.info(
                "Starting epoch %d/%d",
                epoch,
                args.epochs,
            )

            train_loss = train_one_epoch(
                model=model,
                train_loader=train_loader,
                criterion=criterion,
                optimizer=optimizer,
                scheduler=scheduler,
                ema=ema,
                device=device,
                epoch=epoch,
                epochs=args.epochs,
                accumulate=accumulate,
                use_amp=use_amp,
                writer=writer,
            )

            # Validation and checkpoint selection use the EMA model.
            val_loss, metrics = validate(
                model=ema.ema,
                val_loader=val_loader,
                criterion=criterion,
                device=device,
                epoch=epoch,
                epochs=args.epochs,
                use_amp=use_amp,
            )

            log_validation_results(
                writer=writer,
                epoch=epoch,
                val_loss=val_loss,
                metrics=metrics,
            )

            logger.info(
                "Epoch %d/%d | "
                "train_loss=%.4f | "
                "val_loss=%.4f | "
                "accuracy=%.4f | "
                "precision=%.4f | "
                "recall=%.4f | "
                "f1=%.4f",
                epoch,
                args.epochs,
                train_loss,
                val_loss,
                metrics["accuracy"],
                metrics["precision"],
                metrics["recall"],
                metrics["f1"],
            )

            logger.info(
                "Confusion matrix | "
                "TP=%d | TN=%d | FP=%d | FN=%d",
                metrics["tp"],
                metrics["tn"],
                metrics["fp"],
                metrics["fn"],
            )

            save_checkpoint(
                checkpoint_path=last_checkpoint,
                epoch=epoch,
                model=ema.ema,
                metrics=metrics,
                train_loss=train_loss,
                val_loss=val_loss,
            )

            if metrics["f1"] > best_f1:

                best_f1 = metrics["f1"]

                save_checkpoint(
                    checkpoint_path=best_checkpoint,
                    epoch=epoch,
                    model=ema.ema,
                    metrics=metrics,
                    train_loss=train_loss,
                    val_loss=val_loss,
                )

                logger.info(
                    "New best model: epoch=%d, F1=%.4f",
                    epoch,
                    best_f1,
                )

        logger.info(
            "Training completed. Best validation F1: %.4f",
            best_f1,
        )

        logger.info(
            "Best checkpoint: %s",
            best_checkpoint,
        )

        logger.info(
            "Last checkpoint: %s",
            last_checkpoint,
        )

    finally:

        writer.close()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()


def parse_arguments():
    """
    Define command-line arguments for a single BlindSpot training run.
    """

    parser = argparse.ArgumentParser(
        description=(
            "Train the BlindSpot occupancy-classification model."
        )
    )

    parser.add_argument(
        "--train-metadata",
        type=Path,
        required=True,
        help="Path to train_metadata.json",
    )

    parser.add_argument(
        "--val-metadata",
        type=Path,
        required=True,
        help="Path to val_metadata.json",
    )

    parser.add_argument(
        "--autospeed-checkpoint",
        type=str,
        default=None,
        help=(
            "Optional AutoSpeed checkpoint used to initialize "
            "the BlindSpot backbone."
        ),
    )

    parser.add_argument(
        "--runs-dir",
        type=Path,
        default=Path("runs/blindspot"),
        help="Directory containing BlindSpot training runs.",
    )

    parser.add_argument(
        "--output-subdir",
        type=str,
        default=None,
        help=(
            "Optional fixed run-directory name. "
            "An existing directory with this name is replaced."
        ),
    )

    parser.add_argument(
        "--epochs",
        type=int,
        default=30,
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=8,
    )

    parser.add_argument(
        "--val-batch-size",
        type=int,
        default=8,
    )

    parser.add_argument(
        "--num-workers",
        type=int,
        default=4,
    )

    parser.add_argument(
        "--max-lr",
        type=float,
        default=DEFAULT_MAX_LR,
    )

    parser.add_argument(
        "--min-lr",
        type=float,
        default=DEFAULT_MIN_LR,
    )

    parser.add_argument(
        "--momentum",
        type=float,
        default=DEFAULT_MOMENTUM,
    )

    parser.add_argument(
        "--weight-decay",
        type=float,
        default=DEFAULT_WEIGHT_DECAY,
    )

    parser.add_argument(
        "--warmup-epochs",
        type=float,
        default=DEFAULT_WARMUP_EPOCHS,
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=0,
    )

    parser.add_argument(
        "--fp32",
        action="store_true",
        help="Disable mixed precision and train in FP32.",
    )

    return parser.parse_args()


if __name__ == "__main__":

    training_args = parse_arguments()

    train(
        training_args
    )